add null check for curSourceFile and log error if curSourceFile is null (#75)
Fixes
[ENT-226](https://linear.app/hasura/issue/ENT-226/connector-crash-reported-by-ngs-super)

An attempt at fixing the following error:
```
[02:42:41.897] FATAL (1): Cannot set properties of undefined (setting 'fileContent')
    err: {
      "type": "TypeError",
      "message": "Cannot set properties of undefined (setting 'fileContent')",
      "stack":
          TypeError: Cannot set properties of undefined (setting 'fileContent')
              at Object.fixImports (/app/dist/app/parser/typescript/cleanup.js:48:26)
              at cleanupAndFormat (/app/dist/app/writer/functions-ts-writer.js:49:13)
              at writeContentToFile (/app/dist/app/writer/functions-ts-writer.js:45:11)
              at Object.writeToFileSystem (/app/dist/app/writer/functions-ts-writer.js:35:15)
              at Object.writeToFileSystem (/app/dist/app/writer/index.js:39:31)
              at Object.runApp (/app/dist/app/index.js:45:18)
              at async main (/app/dist/cli/update.js:73:9)
    }
```

**NOTE**
I have not been able to reproduce this issue, this fix is a best case
attempt by studying the crash logs